# Generated by Django 4.2.7 on 2025-08-26 22:45

from django.db import migrations, models
import usuarios.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_grupo_obriga_reconhecimento_facial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto_perfil_facial',
            field=models.ImageField(blank=True, help_text='Upload de uma foto clara do rosto (JPG/PNG, máx. 5MB, mín. 100x100px)', null=True, upload_to='faces/%Y/%m/', validators=[usuarios.models.validate_facial_image], verbose_name='Foto de Referência Facial'),
        ),
    ]
